### ISSUE TITLE
awslogs service fails to start on Debian 9 with systemd

### ISSUE THREAD

**Issue by bailey86** [tartansandal/ansible-role-awslogs-setup#2]
Error in log is /usr/bin/env: ‘/bin/nice’: No such file or directory

This looks like it is related to tartansandal.awslogs-setup/templates/launcher.sh.j2
because running:
# env /bin/nice
gives me the error:
'env: ‘/bin/nice’: No such file or directory' as well

**Comment by bailey86** [comment]
Actually - I think this is more to do with the fact that on Debian 'nice' is in /usr/bin/nice and your launher template is looking for /bin/nice

This must be similar to how you have allowed for the other paths 'ps, cat, grep,etc' to be changed.  I think the same sort of configuration is needed for the 'nice' command.

**Comment by tartansandal** [comment]
Thanks for spotting that @bailey86 !  I'll add another default variable to cover that case.

**Comment by tartansandal** [comment]
Just patched to fix this. Thanks @bailey86 :-)
